### ISSUE TITLE
Cannot deploy eVDC on testnet

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#1004]
Tried to deploy a eVDC via the deployer. got error message:
![image](https://user-images.githubusercontent.com/13766992/105495006-0b29a480-5cd5-11eb-8d9b-fd1a2b1d81a8.png)

**Comment by hossnys** [comment]
this log maybe related also as wallet creation is not working fine :

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://explorer.testnet.grid.tf/api/v1/users/2714
127.0.0.1 - - [2021-01-23 13:04:50] "GET /admin/admin/list_identities HTTP/1.0" 200 1064 3.632785
127.0.0.1 - - [2021-01-23 13:04:56] "GET /authorized HTTP/1.0" 200 220 0.021698
2021-01-23 13:04:56.671 | INFO     | jumpscale.servers.gedis.server:_on_connection:270 - Executing method get_notifications_count from actor admin_admin to client ('127.0.0.1', 38890)
127.0.0.1 - - [2021-01-23 13:04:56] "GET /admin/admin/get_notifications_count HTTP/1.0" 200 332 0.005693
127.0.0.1 - - [2021-01-23 13:04:58] "GET /authorized HTTP/1.0" 200 220 0.006361
2021-01-23 13:04:58.386 | INFO     | jumpscale.servers.gedis.server:_on_connection:270 - Executing method create_wallet from actor admin_wallet to client ('127.0.0.1', 38890)
127.0.0.1 - - [2021-01-23 13:05:06] "GET /authorized HTTP/1.0" 200 220 0.024149
2021-01-23 13:05:06.675 | INFO     | jumpscale.servers.gedis.server:_on_connection:270 - Executing method get_notifications_count from actor admin_admin to client ('127.0.0.1', 39322)
127.0.0.1 - - [2021-01-23 13:05:06] "GET /admin/admin/get_notifications_count HTTP/1.0" 200 332 0.004111
2021-01-23 13:05:08.585 | ERROR    | jumpscale.servers.gedis.server:_execute:231 - error while executing <bound method Wallet.create_wallet of <wallet.Wallet object at 0x7f3c9ad86e50>>
Traceback (most recent call last):

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/admin/actors/wallet.py", line 14, in create_wallet
    wallet.activate_through_threefold_service()
    │      └ <function Stellar.activate_through_threefold_service at 0x7f3c9c153710>
    └ Stellar(
        instance_name='test111111',
        network=<Network.STD: 'STD'>,
        address='GBFLDMXOQIVQPQSJ5RZCE37KGVLJZBFLHI3JFX2C53I...

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/stellar/stellar.py", line 249, in activate_through_threefold_service
    self.sign(xdr, submit=True)
    │    │    └ 'AAAAAgAAAACUs1jkxPVfbOLVRpiOxMbN3mJHO9wPQ2cD4UMDrsjtlQAAAZABwCaHAABKYQAAAAEAAAAAAAAAAAAAAABgDB8wAAAAAAAAAAQAAAAAAAAAEAAAAABK...
    │    └ <function Stellar.sign at 0x7f3c9c154050>
    └ Stellar(
        instance_name='test111111',
        network=<Network.STD: 'STD'>,
        address='GBFLDMXOQIVQPQSJ5RZCE37KGVLJZBFLHI3JFX2C53I...

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/stellar/stellar.py", line 748, in sign
    horizon_server.submit_transaction(tx)
    │              │                  └ <stellar_sdk.transaction_envelope.TransactionEnvelope object at 0x7f3c9828c590>
    │              └ <function Server.submit_transaction at 0x7f3c9c144b90>
    └ <jumpscale.clients.stellar.wrapped.Server object at 0x7f3c98429e50>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/stellar/wrapped.py", line 47, in submit_transaction
    raise e

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/stellar/wrapped.py", line 34, in submit_transaction
    return super().submit_transaction(transaction_envelope)
                                      └ <stellar_sdk.transaction_envelope.TransactionEnvelope object at 0x7f3c9828c590>
  File "/usr/local/lib/python3.7/dist-packages/stellar_sdk/server.py", line 111, in submit_transaction
    transaction_envelope, skip_memo_required_check 
    │                     └ False
    └ <stellar_sdk.transaction_envelope.TransactionEnvelope object at 0x7f3c9828c590>
  File "/usr/local/lib/python3.7/dist-packages/stellar_sdk/server.py", line 129, in __submit_transaction_sync
    raise_request_exception(resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7f3c982c1bd0>
    └ <function raise_request_exception at 0x7f3c9c7b9440>
  File "/usr/local/lib/python3.7/dist-packages/stellar_sdk/exceptions.py", line 209, in raise_request_exception
  raise BadRequestError(response)                                                                                                                                                               [30/1847]
          │               └ <stellar_sdk.client.response.Response object at 0x7f3c982c1bd0>
          └ <class 'stellar_sdk.exceptions.BadRequestError'>

stellar_sdk.exceptions.BadRequestError: {
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://w
ww.stellar.org/developers/guides/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAgAAAACUs1jkxPVfbOLVRpiOxMbN3mJHO9wPQ2cD4UMDrsjtlQAAAZABwCaHAABKYQAAAAEAAAAAAAAAAAAAAABgDB8wAAAAAAAAAAQAAAAAAAAAEAAAAABKsbLugisHwknsciJv6jVWnISrOjaS30Lu0E3zSGdjwgAAAAAAAAAAAAAAAE
qxsu6CKwfCSexyIm/qNVachKs6NpLfQu7QTfNIZ2PCAAAAAAAAAAAAAAABAAAAAEqxsu6CKwfCSexyIm/qNVachKs6NpLfQu7QTfNIZ2PCAAAABgAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwf/////////8AAAABAAAAAEqxsu6CKwfCS
exyIm/qNVachKs6NpLfQu7QTfNIZ2PCAAAAEQAAAAAAAAACrsjtlQAAAECX3fsKt5PXxSrcpEgMnJ7j2pDepzJ+ACe/VgL52LxtC3z2bNSUFPZM4UcZRHlQzG8l5L6caQYwxZsPMCeQQrANSGdjwgAAAECW6A2C7pJcJr3TTgz++bBB9IX4ZxRhBBHQX6+hg9d+75MTyTCW
jYPSVIhsypatnebhoOZ+bIsBvW6rz2dB2nwP",
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_success",
        "op_low_reserve",
        "op_no_source_account",
        "op_no_source_account"
      ]
    },
    "result_xdr": "AAAAAAAAAZD/////AAAABAAAAAAAAAAQAAAAAAAAAAAAAAAA/////f////7////+AAAAAA=="
  }
}


During handling of the above exception, another exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
           │       └ (<gevent._socket3.socket object, fd=18, family=2, type=1, proto=0>, ('127.0.0.1', 38890))
           └ <bound method GedisServer._on_connection of GedisServer(
               instance_name='threebot',
               host='127.0.0.1',
               port=16000,
               enab...
  File "/usr/local/lib/python3.7/dist-packages/jumpscale/servers/gedis/server.py", line 279, in _on_connection
    result = self._execute(method, args, kwargs)
    │        │    │        │       │     └ {'name': 'test111111'}
    │        │    │        │       └ []
    │        │    │        └ <bound method Wallet.create_wallet of <wallet.Wallet object at 0x7f3c9ad86e50>>
    │        │    └ <function GedisServer._execute at 0x7f3c9c0d5830>
    │        └ GedisServer(
    │            instance_name='threebot',
    │            host='127.0.0.1',
    │            port=16000,
    │            enable_system_actor=True,
    │            run_async=True,
    │            _a...
    └ {'result': '{"data": 4047}'}
> File "/usr/local/lib/python3.7/dist-packages/jumpscale/servers/gedis/server.py", line 228, in _execute
    response["result"] = method(*args, **kwargs)
    │                    │       │       └ {'name': 'test111111'}
    │                    │       └ []
    │                    └ <bound method Wallet.create_wallet of <wallet.Wallet object at 0x7f3c9ad86e50>>
    └ {}
  File "/usr/local/lib/python3.7/dist-packages/jumpscale/servers/gedis/baseactor.py", line 25, in wrapper
    result = func(*bound.args, **bound.kwargs)
             │     │     │       │     └ <property object at 0x7f3ca0ad6d70>
             │     │     │       └ <BoundArguments (self=<wallet.Wallet object at 0x7f3c9ad86e50>, name='test111111')>
             │     │     └ <property object at 0x7f3ca0ad6d10>
             │     └ <BoundArguments (self=<wallet.Wallet object at 0x7f3c9ad86e50>, name='test111111')>
             └ <function Wallet.create_wallet at 0x7f3c9ad32290>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/admin/actors/wallet.py", line 17, in create_wallet
    raise j.exceptions.JSException("Error on wallet activation")
          │ └ <property object at 0x7f3c9f66ce30>
          └ <jumpscale.loader.J object at 0x7f3c9f673090>

jumpscale.core.exceptions.exceptions.JSException: Error on wallet activation
```

**Comment by AhmedHanafy725** [comment]
The activation service fails to activate the new wallets
![image](https://user-images.githubusercontent.com/41957921/105579672-7edcb780-5d90-11eb-98a5-57971274cbb7.png)


So an activation wallet is used in the VDC machine to activate the new wallets which it didn't have enough funds (2.5 XLMs).

```
JS-NG> j.clients.stellar.activation_wallet.get_balance()                                          
Balances
  514.5372840 TFT:GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47
  2.5829100 XLM
```

**Comment by xmonader** [comment]
ِActivation wallet been funded with 200XLMs

**Comment by weynandkuijpers** [comment]
Just deployed a eVDC solution - so all good.
