### ISSUE TITLE
test tf directory client

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#159]

**Comment by abom** [comment]
The api/client is working, but the client factory doesn't work (a problem in base classes):

```
JSX> j.clients.threefold_directory.farmers()                                                             
Traceback (most recent call last):                                                                       
  File "<stdin>", line 1, in <module>                                                                    
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 206, in __getattr__    
    return self.__getattribute__(name)                                                                   
  File "/sandbox/lib/jumpscale/Jumpscale/clients/threefold_directory/GridCapacityFactory.py", line 64, in
 farmers                                                                                                 
    return [item.as_dict() for item in self._farmers]                                                    
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 206, in __getattr__    
    return self.__getattribute__(name)                                                                   
  File "/sandbox/lib/jumpscale/Jumpscale/clients/threefold_directory/GridCapacityFactory.py", line 50, in
 _farmers                                                                                                
    return self._cache.get("_farmers", method=do, expire=600)                                            
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 206, in __getattr__    
    return self.__getattribute__(name)                                                                   
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 224, in _cache                
    if self._cache_ is None:                                                                             
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py", line 206, in __getattr__    
    return self.__getattribute__(name)                                                                   
AttributeError: 'GridCapacityFactory' object has no attribute '_cache_'                                  
                                                                                                         
'GridCapacityFactory' object has no attribute '_cache_'                                                  
```
