### ISSUE TITLE
Should be able to install jsx on a docker when the host is ubuntu16

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#232]
## Scenario:
1- Run this command from ubuntu 16 machine to install jsx on a docker 
`python3 /sandbox/code/github/threefoldtech/jumpscaleX/install/install.py -3 --portrange=3 --name=test -d -y -c`

## Result
```root
Traceback (most recent call last):
  File "install/install.py", line 19, in <module>
    IT = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/data/jumpscaleX/install/InstallTools.py", line 2095, in <module>
    MyEnv._init()
  File "/mnt/data/jumpscaleX/install/InstallTools.py", line 1703, in _init
    MyEnv.check_platform()
  File "/mnt/data/jumpscaleX/install/InstallTools.py", line 1654, in check_platform
    UbuntuInstall.ensure_version()
  File "/mnt/data/jumpscaleX/install/InstallTools.py", line 1396, in ensure_version
    raise RuntimeError("Your distribution is not supported. Only Ubuntu Bionic is supported.")
RuntimeError: Your distribution is not supported. Only Ubuntu Bionic is supported.
```

**Comment by rkhamis** [comment]
➤ Abdelrahman Ghanem commented:

@despiegk Please don't unassign anyone working on something before discussing what's wrong exactly, and see if he can do it him self (respecting human effort).
