### ISSUE TITLE
openvcloud client

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#275]
## make sure client is properly implemented 
* implement j.client using our new config mgmt
  * [learn how to do it in template for client ](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by rkhamis** [comment]
➤ Rob Van Mieghem commented:

token = j.clients.openvcloud.getJWTTokenFromItsYouOnline('qwertyui', 'qwertyu')
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/sandbox/lib/jumpscale/Jumpscale/jumpscale_generated.py", line 498, in openvcloud
 self._openvcloud =  OVCClientFactory()
 File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSFactoryBase.py", line 13, in __init__
 obj = kl(parent=self)
 File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfig.py", line 24, in __init__
 self._model = self._parent._model
AttributeError: 'OVCClientFactory' object has no attribute '_model'

'OVCClientFactory' object has no attribute '_model'The itsyouonline client should also no longer be in there as it is in j.clients.itsyouonline
