### ISSUE TITLE
chatbot improvements 10.2 [development_fixes]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#403]
## improvements

- [x] need progress core widget (not the html trick) (`bot.loading_show`, `md_show_update` are implemented)
- [x] [implement j.data.countries to return list of names](https://github.com/threefoldtech/jumpscaleX_core/issues/280) 
- [x] need dropdown for countries (so need to support many countries, need to be a basic component)
- [x] need dropdown for many items with autocomplete (can be used for e.g. countries) 
[TODO: improve colors]

## questions

- are multiple steps still supported?

## is not like a DSL

see /sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/servers/threebot/base_chatflows/food_get.py

```python
def chat(bot):
    """
    to call http://localhost:5050/chat/session/food_get
    """
    html = """\
# Loading food...
 <div class="progress">
  <div class="progress-bar active" role="progressbar" aria-valuenow="{0}"
  aria-valuemin="0" aria-valuemax="100" style="width:{0}%">
    {0}%
  </div>
</div> 
"""

    res = {}
    waittime = bot.int_ask("Wait time")
    for x in range(waittime):
        bot.md_show_update(html.format((x / waittime) * 100))
        gevent.sleep(1)

    form = bot.new_form()
    food = form.string_ask("What do you need to eat?")
    amount = form.int_ask("Enter the amount you need to eat from %s in grams:" % food)
    sides = form.multi_choice("Choose your side dishes: ", ["rice", "fries", "saute", "mashed potato"])
    drink = form.single_choice("Choose your Drink: ", ["tea", "coffee", "lemon"])
    form.ask()

    res = """
    # You have ordered: 
    - {{amount.value}} grams, with sides {{sides.value}} and {{drink.value}} drink
    ### Click next 
    for the final step which will redirect you to threefold.me
    """
    res = j.tools.jinja2.template_render(text=j.core.text.strip(res), **locals())
    bot.md_show(res)
    bot.redirect("https://threefold.me")

```

not good

- jinja2 rendering
- html in the chatflow, needs to be hidden

**Comment by xmonader** [comment]
- I made the multiple steps one to be the default
- example for forms is food_get_form
- added bot.template_render to hide jinja from the dsl
- html moved into `bot.loading_show` function

**Comment by xmonader** [comment]
- j.data.countries implemented here 908ce4f65bab8ac8e7cccc0d893c3030bf333caa
- drop_down_country 5f5c34f473633341ec75dea4b7140a10cd818210

**Comment by xmonader** [comment]
@despiegk I'll move to  `to start` to pickup when you have the time to help with it

**Comment by xmonader** [comment]
state mgmt will be in 10.3

**Comment by Pishoy** [comment]
@xmonader is it merged to development or verify it in development_chatbot ?

**Comment by xmonader** [comment]
check on development_fixes

**Comment by Pishoy** [comment]
food_get is stuck as below picture 
```
JSX> cl3 = j.clients.gedis.get(name='default3',host='127.0.0.1', port=8901, package_name="zerobot.packagemanager")                                                                                          
JSX> cl3.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/chatbot_examples')                                                        
JSX> cl3.reload()                                                                                                                                                                                           

```
- threebot logs
```
HUP 37585
*****************************
*** 3BOTSERVER IS RUNNING ***
*****************************
HUP 37585


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.6/dist-packages/bottle_websocket/plugin.py", line 5, in wrapper
    callback(request.environ.get('wsgi.websocket'), *args, **kwargs)
  File "/sandbox/lib/jumpscale/threebot_packages/zerobot/webinterface/bottle/gedis.py", line 21, in gedis_websocket
    message = ws.receive()
AttributeError: 'NoneType' object has no attribute 'receive'

```
- jsx version 
```
3BOTDEVEL:jsxtest:jumpscaleX_core: git log -1
commit 1e6a2ca5464b5904c91398822d67822a61e72f84 (HEAD -> development_fixes, origin/development_fixes)
Author: Dina-Abd-Elrahman <dena.elsayad@gmail.com>
Date:   Wed Dec 18 12:50:41 2019 +0200

    sshagent test cases
3BOTDEVEL:jsxtest:jumpscaleX_core: git log -1^C
3BOTDEVEL:jsxtest:jumpscaleX_core: cd ../jumpscaleX_threebot/
3BOTDEVEL:jsxtest:jumpscaleX_threebot: git log -1
commit aaa8609a5d797abca89130dd1f887afdb4bfbd4c (HEAD -> development_fixes, origin/development_fixes)
Merge: 6de20843 a73e2f8f
Author: serboctor <boctor.sarah@gmail.com>
Date:   Tue Dec 17 15:59:16 2019 +0200

    Merge branch 'development_fixes' of github.com:threefoldtech/jumpscaleX_threebot into development_fixes

```
![image](https://user-images.githubusercontent.com/21987477/71083488-ccedb780-219b-11ea-92c0-ba8b628b509a.png)

**Comment by xmonader** [comment]
Tested against wrong commits. closing.
